### ISSUE TITLE
include min and max metrics for prometheus quantile metrics

### ISSUE THREAD

**Issue by weyrick** [netboxlabs/pktvisor#558]
In prometheus output, we should include additional `_min` and `_max` metrics for all Quantile based metrics. We currently include `_sum` and `_count` only.

https://github.com/ns1labs/pktvisor/blob/db7b32d1f400273f44a222768d89e622ae5f4fd8/src/Metrics.h#L381

**Comment by leoparente** [comment]
From open metrics:

> Summary
Summaries also measure distributions of discrete events and MAY be used when Histograms are too expensive and/or an average event size is sufficient. They MAY also be used for backwards compatibility, because some existing instrumentation libraries expose precomputed quantiles and do not support Histograms. Precomputed quantiles SHOULD NOT be used, because quantiles are not aggregatable and the user often can not deduce what timeframe they cover.

> A Summary MetricPoint MAY consist of a Count, Sum, Created, and a set of quantiles. Semantically, Count and Sum values are counters so MUST NOT be NaN or negative. Count MUST be an integer.

> A MetricPoint in a Metric with the type Summary which contains Count or Sum values SHOULD have a Timestamp value called Created. This can help ingestors discern between new metrics and long-running ones it did not see before. Created MUST NOT relate to the collection period of quantile values.

> Quantiles are a map from a quantile to a value. An example is a quantile 0.95 with value 0.2 in a metric called myapp_http_request_duration_seconds which means that the 95th percentile latency is 200ms over an unknown timeframe. If there are no events in the relevant timeframe, the value for a quantile MUST be NaN. A Quantile's Metric's LabelSet MUST NOT have "quantile" label name. Quantiles MUST be between 0 and 1 inclusive. Quantile values MUST NOT be negative. Quantile values SHOULD represent the recent values. Commonly this would be over the last 5-10 minutes.

**Comment by leoparente** [comment]
So adding `max` and `min` inside quantile is not a valid summary metric.. they need to be a separated gauge metric.

**Comment by weyrick** [comment]
Ok which means what, just a different name?

**Comment by leoparente** [comment]
I mean that they would be their own Counter metrics
